name: footware
description: "A Footware Store App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  get: ^4.6.6
  dropdown_button2: ^2.3.9
  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6
  get_storage: ^2.1.1
  otp_text_field_v2: ^1.0.3
  razorpay_flutter: ^1.3.6
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true